In [2]:
#creating a simple insaurence prediction model with proper optimization.
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras

In [4]:
df = pd.read_csv("C:/Users/chira/OneDrive/Desktop/Deep learing/Datasets/insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [15]:
#splitting our data into training and testing.
from sklearn.model_selection import train_test_split
X = df.drop("bought_insurance",axis = 1)
Y = df["bought_insurance"]
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42)
x_train


age  affordibility
17   58              1
22   40              1
11   28              1
13   29              0
15   55              1
1    25              0
4    46              1
5    56              1
2    47              1
16   25              0
23   45              1
3    52              0
26   23              1
24   50              1
18   19              0
27   46              1
20   21              1
7    60              0
10   18              1
14   49              1
19   18              1
6    55              0

In [22]:
#lets scale our data to optimize predictions.
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
x_train_scaled = scale.fit_transform(x_train)
x_test_scaled = scale.fit_transform(x_test)
print (x_train_scaled)
print(x_test_scaled)

[[ 1.28296626  0.68313005]
 [ 0.04682359  0.68313005]
 [-0.77727153  0.68313005]
 [-0.70859694 -1.46385011]
 [ 1.07694248  0.68313005]
 [-0.98329531 -1.46385011]
 [ 0.45887115  0.68313005]
 [ 1.14561708  0.68313005]
 [ 0.52754574  0.68313005]
 [-0.98329531 -1.46385011]
 [ 0.39019655  0.68313005]
 [ 0.87091871 -1.46385011]
 [-1.1206445   0.68313005]
 [ 0.73356952  0.68313005]
 [-1.39534287 -1.46385011]
 [ 0.45887115  0.68313005]
 [-1.25799369  0.68313005]
 [ 1.42031545 -1.46385011]
 [-1.46401746  0.68313005]
 [ 0.66489493  0.68313005]
 [-1.46401746  0.68313005]
 [ 1.07694248 -1.46385011]]
[[ 1.10125654  0.70710678]
 [ 0.69553044  0.70710678]
 [ 1.15921741  0.70710678]
 [-0.92737392 -1.41421356]
 [-1.15921741  0.70710678]
 [-0.86941305 -1.41421356]]


In [26]:
#time to train our neural network
model = keras.Sequential([
    keras.layers.Dense(10,input_shape=(2,),activation = 'relu',kernel_initializer = 'ones',bias_initializer = 'zeros'),
    keras.layers.Dense(1,input_shape=(2,),activation = 'sigmoid')
])
model.compile(optimizer = 'adam',
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])
model.fit(x_train_scaled,y_train,epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 399ms/step - loss: 1.2276 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2202 - accuracy: 0.1364
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.2129 - accuracy: 0.1364
Epoch 4/1000
1/1 [==============================] - 0s 5ms/step - loss: 1.2055 - accuracy: 0.1364
Epoch 5/1000
1/1 [==============================] - 0s 5ms/step - loss: 1.1982 - accuracy: 0.1364
Epoch 6/1000
1/1 [==============================] - 0s 550us/step - loss: 1.1909 - accuracy: 0.1364
Epoch 7/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.1837 - accuracy: 0.1364
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.1765 - accuracy: 0.1364
Epoch 9/1000
1/1 [==============================] - 0s 7ms/step - loss: 1.1694 - accuracy: 0.1364
Epoch 10/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.1622 - accuracy: 0.1364
Epoch 11/1000
1

In [31]:
#lets check model performance on testset
model.evaluate(x_test_scaled,y_test)


1/1 [==============================] - 0s 111ms/step - loss: 0.2033 - accuracy: 1.0000


[0.20330379903316498, 1.0]

In [34]:
predictions = model.predict(x_test_scaled)
threshold = 0.5
binary_predictions = (predictions >= threshold).astype(int)# need to convert continous prediction values of sigmoid function to discrete values.
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(binary_predictions,y_test)
print(accuracy*100)
# great , we have gotten an amazing accuracy.

1/1 [==============================] - 0s 10ms/step
100.0


In [41]:
#cheching model weight and biases.
weights, biases = model.layers[0].get_weights()
weights1, biases1 = model.layers[1].get_weights()
print(weights, biases)# for relu layer
print(weights1, biases1)# for sigmoid layer

[[1.5812846  1.3574146  0.8068142  1.553558   1.3856728  1.5856433
  0.80644494 0.8637627  0.8591259  0.8388092 ]
 [1.2283164  1.1191899  0.8088125  1.1746539  1.1333944  1.2386528
  0.808452   0.8644329  0.859911   0.8400868 ]] [ 0.31913683  0.25915775 -0.1911868   0.31130153  0.26714307  0.32335877
 -0.19154914 -0.13556784 -0.14008896 -0.15991323]
[[ 0.26463622]
 [ 0.76266605]
 [-0.464959  ]
 [ 0.2362123 ]
 [ 0.5281545 ]
 [ 0.2789759 ]
 [-0.4760565 ]
 [-0.01814801]
 [-0.02879728]
 [-0.0963792 ]] [-0.84156644]
